baseurl = "https://tomhardwicke.netlify.com/"
title = "Tom Hardwicke"
author = "Tom Hardwicke"
canonifyurls = true
languagecode = "en"
theme = "hugo-black-and-light-theme"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Tom Hardwicke"
  position = "Postdoctoral Fellow"
  department = "Meta-Research Innovation Center at Stanford (METRICS)"
  university = "Stanford University"

[[menu.main]]
    name = "CV &#xb7"
    url  = "/docs/Hardwicke_cv.pdf"
    weight = 1
[[menu.main]]
    name = "Publications &#xb7"
    url  = "/publications/"
    weight = 2
[[menu.main]]
    name = "Contact"
    url  = "mailto:tom.hardwicke@stanford.edu"
    weight = 3
